from .SD35Plus_node import NODE_CLASS_MAPPINGS as PLUS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as PLUS_DISPLAY_MAPPINGS

from .SD35S_node import NODE_CLASS_MAPPINGS as S_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as S_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS = {**PLUS_MAPPINGS, **S_MAPPINGS}

NODE_DISPLAY_NAME_MAPPINGS = {**PLUS_DISPLAY_MAPPINGS, **S_DISPLAY_MAPPINGS}
__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
